
language: php

# sudo: required

php:
  - 7.1

env: DB=mysql

before_script:
  - composer install
  - composer update
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

notifications:
  email: true